name: test-and-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Run tests (CTest)
        run: ctest --test-dir build --output-on-failure -C ${{ env.BUILD_TYPE }}

  package:
    name: Package header & Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create a Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare header-only bundle
        run: |
          mkdir -p dist/src
          cp src/c-log.h dist/src/c-log.h
          (cd dist && zip -r "c-log-${{ github.ref_name }}.zip" src)
          (cd dist && tar -czf "c-log-${{ github.ref_name }}.tar.gz" src)
          (cd dist && sha256sum c-log-* > SHA256SUMS)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: c-log-${{ github.ref_name }}
          path: dist/*

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          files: |
            dist/c-log-${{ github.ref_name }}.zip
            dist/c-log-${{ github.ref_name }}.tar.gz
            dist/SHA256SUMS
